<?php
// More Dèmos sentences
return [
    // Culture & society
    "Most people mistake comfort for happiness.",
    "The herd is always late to the truth.",
    "If your friends agree with you on everything, you have no friends — just mirrors.",
    "Morality is often just obedience in disguise.",
    "Silence isn’t neutrality, it’s consent.",
    "Nobody wants the truth if a good lie feels better.",
    "The louder the virtue signal, the dirtier the secret.",
    "Weak people wait for permission.",
    "Tradition is peer pressure from dead people — sometimes necessary, sometimes nonsense.",
    "Convenience culture breeds weak minds.",
    "The algorithm is raising your kids.",
    "Victimhood is a modern currency with infinite inflation.",
    "Culture is downstream from whoever owns the microphones.",
    "You don’t own your time if your phone owns your attention.",
    "The desire to be liked is the enemy of authenticity.",
    "Mass opinion is a product, not a reflection.",

    // Power & politics
    "The state’s job is to create problems it pretends to solve.",
    "Opposition parties are controlled leaks for public rage.",
    "The media doesn’t cover stories, it selects narratives.",
    "Any system that can be abused, will be.",
    "When propaganda stops working, force starts.",
    "Tyrants call themselves protectors.",
    "Political correctness is a muzzle with good branding.",
    "In politics, sincerity is staged and outrage is monetized.",
    "There are no conspiracies — and yet nothing happens by accident.",
    "You’ll know a government policy is bad when it’s sold as 'for your safety.'",
    "Freedom isn’t given, it’s taken, and rarely returned.",
    "Mass surveillance is authoritarianism with better UX.",
    "Leaders don’t serve nations. They serve agendas.",
    "If they can’t control you, they’ll discredit you.",
    "The price of liberty is constant paranoia.",
    "The law is not about justice. It’s about control.",

    // Finance & power
    "In the economy, the house always wins.",
    "Hyperinflation starts slow — then it’s overnight.",
    "A billionaire’s philanthropy is a PR expense.",
    "Money buys power. Power buys immunity.",
    "Most taxes fund the system that exploits you.",
    "Your debt is someone else's passive income.",
    "If your paycheck controls your opinions, you’re not free.",
    "Assets print wealth. Labor prints exhaustion.",
    "The middle class was an experiment. It’s being dismantled.",
    "Wealth gaps are policy, not accidents.",
    "Your pension is a promise they’ll break.",
    "If you don’t own equity, you are the product.",
    "Banks fail safely when the rules are written for them.",
    "Savings accounts are slow-motion theft.",
    "Inflation is the invisible tax on the obedient.",
    "Every crash is a transfer, not a loss.",

    // Tech & digital culture
    "Big Tech sells addiction with a smile.",
    "The future isn’t decentralized — unless you build it yourself.",
    "Deepfakes will destroy reality long before AI takes your job.",
    "You think you’re using social media — it’s using you.",
    "The only thing faster than technology is your loss of privacy.",
    "Algorithms won’t replace governments, they’ll work for them.",
    "Your digital history is a surveillance weapon waiting to be activated.",
    "The app you trust most is the one that spies best.",
    "In the data economy, your secrets have a market price.",
    "The algorithm doesn’t care about your truth.",
    "Convenience now, consequences later.",
    "AI isn’t scary because it’s smart — it’s scary because it’s obedient.",
    "Big Tech isn’t left or right. It’s whoever pays.",
    "Terms of service are the new laws you didn’t vote for.",
    "Your privacy settings are a placebo.",
    "Smart devices are surveillance devices with a helpful excuse.",

    // Human nature & meta
    "People don't change — incentives do.",
    "Comfort is the most effective form of control.",
    "Most of what you call 'beliefs' are habits you never challenged.",
    "Everyone loves a rebel until they rebel against them.",
    "Your enemy isn't who you think. It’s who you refuse to see.",
    "The most dangerous people are the ones who think they're righteous.",
    "Men are governed by fear more than reason.",
    "Civilizations fall the same way trust does — slowly, then all at once.",
    "Every generation inherits the lies the last one was too afraid to admit.",
    "The desire for safety births tyrants.",
    "Inertia is a more powerful force than evil.",
    "The truth will cost you friends, opportunities, and comfort.",
    "Your chains feel lighter when everyone else wears them too.",
    "If your truth requires silence, it’s a lie.",
    "Courage is rare because the price is high.",
    "History repeats itself because arrogance blinds memory.",
];
